apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: ibm-vpc-block-csi-driver
  name: vpc-block-provisioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vpc-block-provisioner-role
subjects:
  - kind: ServiceAccount
    name: ibm-vpc-block-controller-sa
    namespace: openshift-cluster-csi-drivers
