---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vpc-block-external-resizer-binding
  labels:
    app: ibm-vpc-block-csi-driver
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
     version: (( grab $BUILD_VERSION || "dev" ))
subjects:
  - kind: ServiceAccount
    name: ibm-vpc-block-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: vpc-block-external-resizer-role
  apiGroup: rbac.authorization.k8s.io
