---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vpc-block-external-resizer-binding
  labels:
    app: ibm-vpc-block-csi-driver
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
     version: 2.0.3_354
subjects:
  - kind: ServiceAccount
    name: ibm-vpc-block-controller-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: vpc-block-external-resizer-role
  apiGroup: rbac.authorization.k8s.io
